#! /bin/sh
xsetroot -cursor_name left_ptr &
setxkbmap br &
feh --bg-scale ~/wallpaper.png &
dunst &
picom &
polkit-dumb-agent &
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV 

bspc config border_width         5
bspc config window_gap           12
bspc config split_ratio          0.5

bspc config active_border_color "#1d2021"
bspc config focused_border_color "#928374"
