#! /bin/sh
sxhkd &
polybar -r example &
xrandr --output VGA-1 --mode 1440x900 --rate 75 &
feh --bg-scale ~/wallpaper.jpg &

bspc monitor -d I II III IV V

bspc config border_width         1
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
